name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make build

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run unit tests
      run: make test-unit

    - name: Run benchmark sim tests
      run: make test-sim-benchmark

    - name: Run determinism sim tests
      run: make test-sim-determinism
